Use the full ooxml-schemas for full document indexing
As our documents contain features not present in the poi-ooxml
(see http://poi.apache.org/faq.html#faq-N10025) we were getting
java.lang.NoClassDefFoundError: org/openxmlformats/schemas/...
so, switched to the full ooxml-schemas as downloaded from
http://mvnrepository.com/artifact/org.apache.poi/ooxml-schemas